# Generated by Django 3.1.6 on 2021-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtn4VAG1j1mzMFukZ4KFbAqxirEvDTqdMjA&usqp=CAU'),
        ),
    ]
