# Generated by Django 3.1.6 on 2021-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQif6kzNl9lDfDPn3rvrt_ZQykb0tU1ZU3KlA&usqp=CAU'),
        ),
    ]
